# Generated by Django 3.2.4 on 2021-06-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0002_rename_dni_turista_nacionalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turista',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
