# Generated by Django 3.2.4 on 2021-06-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0003_rename_nombre_turista_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='vacunadoCovid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
