# Generated by Django 3.2.4 on 2021-06-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0005_rename_vacunadocovid_turista_vacunado_covid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turista',
            name='vacunado_Covid',
            field=models.BooleanField(default=True),
        ),
    ]
